#!/bin/sh -eux

. $(dirname $0)/../core/runner.sh

banner invoke $0

mountebank_port=$(cat $MOUNTEBANK_PORTFILE)
tatooine_port=$(cat $TATOOINE_PORTFILE)

export UPLOAD_DIR="${RUNDIR}/upload"
unset DOWNLOAD_DIR
export AMBIATA_API_KEY=$RANDOM
export AMBIATA_FEED=$RANDOM
export AMBIATA_API_ENDPOINT=http://localhost:${tatooine_port}
export ONESHOT=1
export http_proxy=http://localhost:${mountebank_port}

RESULT=$($AMBIATA_CLI upload || exit_endtoend $?)

if [[ "$RESULT" == *"No files to upload." ]]; then
  echo "correct! "$RESULT
else
  echo "incorrect! "$RESULT
  exit_endtoend 1
fi

exit_endtoend 0
